# Generated by Django 2.2 on 2019-04-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_id', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, to='rest_api.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('duration', models.TimeField()),
                ('groups', models.ManyToManyField(blank=True, to='rest_api.Group')),
                ('organisers', models.ManyToManyField(related_name='organisers', to='rest_api.Person')),
                ('people', models.ManyToManyField(blank=True, related_name='attendees', to='rest_api.Person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Room')),
            ],
        ),
    ]
